### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kjhughes** [vanillawc/wc-json#1]
Is this code covered by an MIT license as others in vanillawc?

**Comment by evanplaice** [comment]
Good question

@georges-gomes is it cool if I add the standard @VanillaWC copyright MIT license to this repo?

**Comment by georges-gomes** [comment]
I will 👍 Because it's generated from webcomponents.dev, I need to figure out the best way to achieve this. Bare with me a little bit.

**Comment by kjhughes** [comment]
Ah, so maybe I should ask upstream at [json-element](https://github.com/webcomponents-dev/json-element), or @georges-gomes, will you add a license there?  Thank you.

**Comment by georges-gomes** [comment]
@kjhughes I will add the license there and it will sync back here in GitHub. I have been away from my keyboard but I hope to fix this soon 👍

**Comment by georges-gomes** [comment]
The "source of truth" is here: https://webcomponents.dev/edit/VXr2i1M8U1s4He9bOdII
And there is the MIT license set there. But it just doesn't sync back here with a LICENSE file.

**Comment by kjhughes** [comment]
@georges-gomes, but you meant ISC, no?  (I saw it listed under the fingerprint icon on the left panel [there](https://github.com/webcomponents-dev/json-element).)

I'm a little surprised that the [Github repo](https://github.com/webcomponents-dev/json-element) isn't the source of truth.  (There is no license posted to the repository yet.)

**Comment by georges-gomes** [comment]
@kjhughes sorry for the delay. It's now all synced-up with MIT LICENSE
https://webcomponents.dev/edit/VXr2i1M8U1s4He9bOdII
https://www.npmjs.com/package/@webcomponents-dev/json-element
and this repository of course

**Comment by kjhughes** [comment]
@georges-gomes:  Great, thank you for clarifying the license and also for creating and making your work available!

**Comment by evanplaice** [comment]
I'm closing this since a license has been added. Feel free to reopen if there are still issues.
